import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { formatCoords, getCurrentLocation } from './locationService';
import { getBatteryInfo } from './batteryService';

// ─── Shared utilities ─────────────────────────────────────────────────────────

const esc = (str) =>
  String(str ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');

const formatDate = (iso) => {
  if (!iso) return '';
  const d = new Date(iso);
  return d.toLocaleString('en-AU', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
};

function renderSection(section) {
  const checklistRows = Object.entries(section.checklist || {})
    .map(([k, v]) => `<tr><td>${esc(k)}</td><td>${v ? '✓ Yes' : '✗ No'}</td></tr>`)
    .join('');

  const photosHtml = (section.photos || [])
    .slice(0, 4)
    .map((p, idx) => `<div style="border:1px solid #ccc; padding:8px; margin:8px 0; border-radius:4px;"><strong>Photo ${idx + 1}</strong><br/>${esc(formatDate(p.timestamp))}</div>`)
    .join('');

  return `
    <div style="page-break-inside:avoid; margin-bottom:20px; border:1px solid #ddd; padding:16px; border-radius:8px;">
      <h2 style="margin:0 0 12px; color:#2563EB;">${esc(section.name)}</h2>
      ${section.complete ? '<p style="color:green; font-weight:bold;">✓ Complete</p>' : '<p style="color:orange;">In progress</p>'}
      ${checklistRows ? `<table style="width:100%; border-collapse:collapse;">${checklistRows}</table>` : ''}
      ${section.conditionNotes ? `<p><strong>Notes:</strong> ${esc(section.conditionNotes)}</p>` : ''}
      ${photosHtml}
    </div>`;
}

function buildHtml(report) {
  const completedSections = report.sections.filter((s) => s.complete).length;
  return `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8" />
<title>${esc(report.title)}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color:#333; line-height:1.5; }
  header { background: linear-gradient(135deg, #2563EB, #1E40AF); color: white; padding: 24px; border-radius: 8px; margin-bottom: 24px; }
  header h1 { margin: 0; font-size: 28px; }
  header p { margin: 8px 0 0; opacity: 0.9; }
  .meta { background: #f3f4f6; padding: 16px; border-radius: 8px; margin-bottom: 24px; }
  .meta div { margin-bottom: 8px; }
  .meta strong { color: #6b7280; font-size: 12px; text-transform: uppercase; }
  table { border-collapse: collapse; width: 100%; }
  td { padding: 8px; border-bottom: 1px solid #e5e7eb; }
  @page { size: A4; margin: 15mm; }
</style>
</head>
<body>
<header>
  <p style="margin:0; font-size:12px;">FieldReportX</p>
  <h1>${esc(report.title)}</h1>
  <p>Rental Inspection Report</p>
</header>

<div class="meta">
  <div><strong>Property:</strong> ${esc(report.propertyAddress)}</div>
  <div><strong>Inspector:</strong> ${esc(report.inspectorName)}</div>
  <div><strong>Date:</strong> ${formatDate(report.createdAt)}</div>
  <div><strong>GPS:</strong> ${esc(formatCoords(report.gpsLocation))}</div>
  <div><strong>Progress:</strong> ${completedSections}/${report.sections.length} sections</div>
</div>

${report.sections.map(renderSection).join('')}

<p style="margin-top:32px; padding-top:16px; border-top:1px solid #ddd; color:#999; font-size:12px;">
Generated by FieldReportX | Report ID: ${esc(report.id)} | ${formatDate(new Date().toISOString())}
</p>
</body>
</html>`;
}

export async function generateReportPdf(report) {
  // Gather live context (location + battery) in parallel while building HTML
  const [html, liveContext] = await Promise.all([
    Promise.resolve(buildHtml(report)),
    Promise.all([
      getCurrentLocation().catch(() => null),
      getBatteryInfo().catch(() => null),
    ]),
  ]);
  const [currentLocation, battery] = liveContext;
  const enrichedHtml = html.replace(
    '</body>',
    `<p style="margin-top:8px; color:#9ca3af; font-size:10px;">
       Generated at: ${formatCoords(currentLocation?.data)} | Battery: ${battery?.percent ?? '?'}%
     </p></body>`
  );
  const { uri } = await Print.printToFileAsync({ html: enrichedHtml, base64: false });
  return uri;
}

export async function shareReportPdf(uri) {
  const available = await Sharing.isAvailableAsync();
  if (!available) throw new Error('Sharing not available');
  await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: 'Share inspection report' });
}

// ─── Generic report PDF (all non-rental types) ────────────────────────────────

const TYPE_COLORS = {
  trades: '#F59E0B',
  legal: '#06B6D4',
  driving: '#8B5CF6',
  rehab: '#EC4899',
  general: '#6366F1',
  service: '#10B981',
};

const TYPE_LABELS = {
  trades: 'Trades Report',
  legal: 'Legal & Forensic Report',
  driving: 'Driving Test Report',
  rehab: 'Patient Rehabilitation Report',
  general: 'General Report',
  service: 'Service Delivery Report',
};

function renderGenericSection(section) {
  const checklistRows = Object.entries(section.checklist || {})
    .map(([k, v]) => `<tr><td style="padding:6px 8px; border-bottom:1px solid #f0f0f0;">${esc(k)}</td><td style="padding:6px 8px; border-bottom:1px solid #f0f0f0; text-align:center;">${v ? '<span style="color:#10b981; font-weight:bold;">✓</span>' : '<span style="color:#ef4444;">✗</span>'}</td></tr>`)
    .join('');

  const checkedCount = Object.values(section.checklist || {}).filter(Boolean).length;
  const totalCount = Object.keys(section.checklist || {}).length;

  const photosHtml = (section.photos || [])
    .slice(0, 6)
    .map((p, idx) => {
      const label = p.type ? `${p.type.charAt(0).toUpperCase() + p.type.slice(1)} ${idx + 1}` : `Photo ${idx + 1}`;
      return `<div style="display:inline-block; border:1px solid #ddd; padding:6px; margin:4px; border-radius:4px; font-size:11px;"><strong>${esc(label)}</strong><br/>${esc(formatDate(p.timestamp))}${p.name ? `<br/>${esc(p.name)}` : ''}</div>`;
    })
    .join('');

  const audioHtml = (section.audioNotes || [])
    .map((a, idx) => `<div style="display:inline-block; border:1px solid #fcd34d; background:#fef3c7; padding:6px; margin:4px; border-radius:4px; font-size:11px;">🎙️ <strong>Audio Note ${idx + 1}</strong><br/>${esc(formatDate(a.timestamp))}</div>`)
    .join('');

  const scoreHtml = section.score !== null
    ? `<p style="font-size:13px;"><strong>Section Score:</strong> <span style="color:#8b5cf6; font-size:16px; font-weight:bold;">${section.score}/100</span></p>`
    : '';

  return `
    <div style="page-break-inside:avoid; margin-bottom:16px; border:1px solid #e5e7eb; padding:16px; border-radius:8px;">
      <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:10px;">
        <h2 style="margin:0; font-size:16px; color:#374151;">${esc(section.name)}</h2>
        <span style="font-size:12px; padding:3px 8px; border-radius:4px; background:${section.complete ? '#d1fae5' : '#fee2e2'}; color:${section.complete ? '#065f46' : '#b91c1c'};">
          ${section.complete ? '✓ Complete' : 'In Progress'} — ${checkedCount}/${totalCount}
        </span>
      </div>
      ${checklistRows ? `<table style="width:100%; border-collapse:collapse; font-size:13px; margin-bottom:8px;">${checklistRows}</table>` : ''}
      ${scoreHtml}
      ${section.conditionNotes ? `<p style="font-size:13px; color:#374151;"><strong>Notes:</strong> ${esc(section.conditionNotes)}</p>` : ''}
      ${photosHtml ? `<div style="margin-top:8px;"><strong style="font-size:12px;">Evidence:</strong><br/>${photosHtml}</div>` : ''}
      ${audioHtml ? `<div style="margin-top:8px;"><strong style="font-size:12px;">Audio Evidence:</strong><br/>${audioHtml}</div>` : ''}
    </div>`;
}

function buildGenericHtml(report) {
  const color = TYPE_COLORS[report.type] || '#2563EB';
  const typeLabel = TYPE_LABELS[report.type] || report.type;
  const completedSections = report.sections.filter((s) => s.complete).length;
  const totalPhotos = report.sections.reduce((sum, s) => sum + (s.photos?.length || 0), 0);
  const totalAudio = report.sections.reduce((sum, s) => sum + (s.audioNotes?.length || 0), 0);

  const scoredSections = report.sections.filter((s) => s.score !== null);
  const overallScore = scoredSections.length > 0
    ? Math.round(scoredSections.reduce((sum, s) => sum + s.score, 0) / scoredSections.length)
    : null;

  const metaRows = Object.entries(report.metadata || {})
    .filter(([, v]) => v)
    .map(([k, v]) => `<div><strong>${esc(k.replace(/([A-Z])/g, ' $1').trim())}:</strong> ${esc(v)}</div>`)
    .join('');

  const signOffHtml = report.signOff?.approvedAt
    ? `<div style="background:#dbeafe; padding:12px; border-radius:6px; margin-top:16px;">
         <strong style="color:#1e40af;">Digital Sign-Off</strong><br/>
         <span style="font-size:13px; color:#1d4ed8;">Signed by: ${esc(report.signOff.userSignature || '')}</span><br/>
         ${report.signOff.supervisorSignature ? `<span style="font-size:13px; color:#1d4ed8;">Supervisor: ${esc(report.signOff.supervisorSignature)}</span><br/>` : ''}
         <span style="font-size:12px; color:#3b82f6;">${formatDate(report.signOff.approvedAt)}</span>
       </div>`
    : '';

  const sensorHtml = report.sensorData
    ? `<div style="background:#f5f3ff; padding:12px; border-radius:6px; margin-bottom:16px;">
         <strong style="color:#7c3aed;">Sensor Data</strong><br/>
         <span style="font-size:13px;">Smoothness Score: <strong>${report.sensorData.smoothnessScore ?? '—'}/100</strong> | Samples: ${report.sensorData.samples} | Duration: ${report.sensorData.durationSeconds}s</span>
       </div>`
    : '';

  const gpsHtml = report.gpsRoute?.length > 0
    ? `<div style="background:#ecfdf5; padding:12px; border-radius:6px; margin-bottom:16px;">
         <strong style="color:#065f46;">GPS Route</strong><br/>
         <span style="font-size:13px;">Total points: ${report.gpsRoute.length} | Start: ${report.gpsRoute[0]?.latitude.toFixed(4)}°, ${report.gpsRoute[0]?.longitude.toFixed(4)}° | End: ${report.gpsRoute[report.gpsRoute.length - 1]?.latitude.toFixed(4)}°, ${report.gpsRoute[report.gpsRoute.length - 1]?.longitude.toFixed(4)}°</span>
       </div>`
    : '';

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8"/>
<title>${esc(report.title)}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color:#1f2937; line-height:1.5; margin:0; }
  header { background:${color}; color:white; padding:24px; border-radius:8px; margin-bottom:20px; }
  header h1 { margin:0 0 4px; font-size:24px; }
  header p { margin:4px 0 0; opacity:0.9; font-size:13px; }
  .meta { background:#f9fafb; padding:14px; border-radius:8px; margin-bottom:20px; font-size:13px; }
  .meta div { margin-bottom:6px; }
  .meta strong { color:#6b7280; font-size:11px; text-transform:uppercase; letter-spacing:0.05em; }
  .stats { display:flex; gap:12px; margin-bottom:20px; }
  .stat { flex:1; text-align:center; background:#f3f4f6; border-radius:8px; padding:12px; }
  .stat-value { font-size:22px; font-weight:700; color:${color}; }
  .stat-label { font-size:11px; color:#6b7280; margin-top:2px; }
  table { border-collapse:collapse; width:100%; }
  @page { size:A4; margin:15mm; }
</style>
</head>
<body>

<header>
  <p>FieldReportX</p>
  <h1>${esc(report.title)}</h1>
  <p>${esc(typeLabel)}</p>
</header>

<div class="meta">
  <div><strong>Created By</strong><br/>${esc(report.createdBy)}</div>
  <div><strong>Date</strong><br/>${formatDate(report.createdAt)}</div>
  ${report.gpsLocation ? `<div><strong>GPS Location</strong><br/>${esc(formatCoords(report.gpsLocation))}</div>` : ''}
  ${metaRows}
  ${report.checksum ? `<div><strong>Report Checksum</strong><br/><code style="font-size:11px;">${esc(report.checksum)}</code></div>` : ''}
  <div><strong>Status</strong><br/>${esc(report.status)}</div>
</div>

<div class="stats">
  <div class="stat">
    <div class="stat-value">${completedSections}/${report.sections.length}</div>
    <div class="stat-label">Sections</div>
  </div>
  <div class="stat">
    <div class="stat-value">${totalPhotos}</div>
    <div class="stat-label">Photos</div>
  </div>
  ${totalAudio > 0 ? `<div class="stat"><div class="stat-value">${totalAudio}</div><div class="stat-label">Audio</div></div>` : ''}
  ${overallScore !== null ? `<div class="stat"><div class="stat-value">${overallScore}/100</div><div class="stat-label">Score</div></div>` : ''}
</div>

${sensorHtml}
${gpsHtml}

<h2 style="font-size:18px; color:#374151; margin-bottom:12px;">Report Sections</h2>
${report.sections.map(renderGenericSection).join('')}

${signOffHtml}

<p style="margin-top:24px; padding-top:12px; border-top:1px solid #e5e7eb; color:#9ca3af; font-size:11px;">
  Generated by FieldReportX | Report ID: ${esc(report.id)} | ${formatDate(new Date().toISOString())}
</p>
</body>
</html>`;
}

export async function generateGenericReportPdf(report) {
  const [html, liveContext] = await Promise.all([
    Promise.resolve(buildGenericHtml(report)),
    Promise.all([
      getCurrentLocation().catch(() => null),
      getBatteryInfo().catch(() => null),
    ]),
  ]);
  const [currentLocation, battery] = liveContext;
  const enrichedHtml = html.replace(
    '</body>',
    `<p style="margin-top:8px; color:#9ca3af; font-size:10px;">
       Generated at: ${formatCoords(currentLocation?.data)} | Battery: ${battery?.percent ?? '?'}%
     </p></body>`
  );
  const { uri } = await Print.printToFileAsync({ html: enrichedHtml, base64: false });
  return uri;
}
